openapi: '3.0.0'
info:
  description: API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
  title: Aeternity Middleware
  version: '2.0'

servers:
  - url: '/v2'
    description: 'V2 version path'
  
components:
  parameters:
    LimitParam:
      in: query
      name: limit
      description: 'Limit paginated resources (max 100)'
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    ScopeParam:
      in: query
      name: scope
      description: 'Scopes results in a txi or generation range'
      schema:
        type: string
        pattern: '(txi|gen):\d+(-\d+)?'
    DirectionParam:
      in: query
      name: direction
      description: 'Sorts results in forwards or backwards direction'
      schema:
        type: string
        enum:
          - forward
          - backward
        
  schemas:
    ErrorResponse:
      description: Error response from the API
      example:
        error: 'invalid id: th_2Twp3pJeVuwQ7cMSdPQRfpAUWwdMiwx6coVMpRaNSuzFRnDZF'
      properties:
        error:
          description: The message of the error raised
          type: string
      required:
        - error
      title: Error response
      type: object
    NotFoundResponse:
      description: Resource not found on the API
      example:
        error: 'not found: th_2Twp3pJeVuwQ7cMSdPQRfpAUWwdMiwx6coVMpRaNSuzFRnDZF'
      properties:
        error:
          description: The message of the error raised
          type: string
      required:
        - error
      title: Not found response
      type: object
    Block:
      example:
        beneficiary: ak_2MR38Zf355m6JtP13T3WEcUcSLVLCxjGvjk6zG95S2mfKohcSS
        hash: kh_uoTGwc4HPzEW9qmiQR1zmVVdHmzU6YmnVvdFe6HvybJJRj7V6
        height: 123008
        info: cb_AAAAAfy4hFE=
        miner: ak_Fqnmm5hRAMaVPWk8wzpodMopZgWghMns4mM7kSV1jgT89p9AV
        nonce: 9223756548132686000
        pow:
          - 12359907
          - 21243613
          - 31370838
          - 34911479
          - 39070315
          - 39375528
          - 45751339
          - 49864206
          - 56785423
          - 70282271
          - 89781776
          - 136985196
          - 140580763
          - 142415353
          - 145306210
          - 148449813
          - 156037609
          - 161568067
          - 170308922
          - 185345129
          - 192805579
          - 214115188
          - 220339679
          - 243288723
          - 258891016
          - 283001743
          - 284306909
          - 286457285
          - 326405486
          - 352963232
          - 377904500
          - 378120539
          - 380987399
          - 388675008
          - 447958786
          - 457602498
          - 465751225
          - 466823982
          - 475416389
          - 491255227
          - 530197445
          - 533633643
        prev_hash: kh_hwin2p8u87mqiK836FixGa1pL9eBkL1Ju37Yi6EUebCgAf8rm
        prev_key_hash: kh_hwin2p8u87mqiK836FixGa1pL9eBkL1Ju37Yi6EUebCgAf8rm
        state_hash: bs_9Dg6mTmiJLpbg9dzgjnNFVidQesvZYZG3dEviUCd4oE1hUcna
        target: 504082055
        time: 1565548832164
        version: 3
      properties:
        beneficiary:
          description: The beneficiary
          type: string
        hash:
          description: The block hash
          type: string
        height:
          description: The block height
          type: integer
        info:
          description: The info
          type: string
        miner:
          description: The miner public key
          type: string
        nonce:
          description: The nonce
          type: string
        pow:
          description: The pow
          type: array
          items:
            type: integer
        prev_hash:
          description: The previous block hash
          type: string
        prev_key_hash:
          description: The previous key block hash
          type: string
        state_hash:
          description: The state hash
          type: string
        target:
          description: The target
          type: integer
        time:
          description: The time
          type: integer
        version:
          description: The version
          type: integer
      title: Block
      type: object
    PaginatedResponse:
      properties:
        next:
          type: string
          example: '/blocks?cursor=123'
        prev: 
          type: string
          example: '/blocks?cursor=234'
    Tx:
      description: Transaction
      properties:
        block_hash:
          description: The block hash
          type: string
        block_height:
          description: The block height
          type: integer
        hash:
          description: The transaction hash
          type: string
        micro_index:
          description: The micro block index
          type: integer
        micro_time:
          description: The unix timestamp
          type: integer
        signatures:
          description: The signatures
          type: array
        tx:
          description: The transaction
          type: object
        tx_index:
          description: The transaction index
          type: integer
      example:
        block_hash: mh_ufiYLdN8am8fBxMnb6xq2K4MQKo4eFSCF5bgixq4EzKMtDUXP
        block_height: 1
        hash: th_2FHxDzpQMRTiRfpYRV3eCcsheHr1sjf9waxk7z6JDTVcgqZRXR
        micro_index: 0
        micro_time: 1543375246712
        signatures:
          - sg_Fipyxq5f3JS9CB3AQVCw1v9skqNBw1cdfe5W3h1t2MkviU19GQckERQZkqkaXWKowdTUvr7B1QbtWdHjJHQcZApwVDdP9
        tx:
          amount: 150425
          fee: 101014
          nonce: 1
          payload: ba_NzkwOTIxLTgwMTAxOGSbElc=
          recipient_id: ak_26dopN3U2zgfJG4Ao4J4ZvLTf5mqr7WAgLAq6WxjxuSapZhQg5
          sender_id: ak_26dopN3U2zgfJG4Ao4J4ZvLTf5mqr7WAgLAq6WxjxuSapZhQg5
          type: SpendTx
          version: 1
        tx_index: 0
    DeltaStat:
      description: DeltaStat
      properties:
        height:
          description: The generation
          type: integer
        auctions_started:
          description: The number of auctions started
          type: integer
        block_reward:
          description: The block reward
          type: integer
        contracts_created:
          description: The number of contracts created
          type: integer
        dev_reward:
          description: The dev reward
          type: integer
        names_activated:
          description: The number of names activated
          type: integer
        names_expired:
          description: The number of names expired
          type: integer
        names_revoked:
          description: The number of names revoked
          type: integer
        oracles_expired:
          description: The number of oracles expired
          type: integer
        oracles_registered:
          description: The number of oracles registered
          type: integer
      example:
        auctions_started: 0
        block_reward: 269973000000000000000
        contracts_created: 0
        dev_reward: 33027000000000000000
        height: 121804
        names_activated: 0
        names_expired: 0
        names_revoked: 0
        oracles_expired: 0
        oracles_registered: 0
    TotalStat:
      type: object
      description: TotalStat
      properties:
        height:
          description: The generation
          type: integer
        auctions_started:
          description: The number of auctions started
          type: integer
        block_reward:
          description: The block reward
          type: integer
        contracts_created:
          description: The number of contracts created
          type: integer
        dev_reward:
          description: The dev reward
          type: integer
        names_activated:
          description: The number of names activated
          type: integer
        names_expired:
          description: The number of names expired
          type: integer
        names_revoked:
          description: The number of names revoked
          type: integer
        oracles_expired:
          description: The number of oracles expired
          type: integer
        oracles_registered:
          description: The number of oracles registered
          type: integer
      example:
        auctions_started: 0
        block_reward: 269973000000000000000
        contracts_created: 0
        dev_reward: 33027000000000000000
        height: 121804
        names_activated: 0
        names_expired: 0
        names_revoked: 0
        oracles_expired: 0
        oracles_registered: 0
    ContractCall:
      description: ContractCall
      properties:
        block_hash:
          type: string
          example: mh_mZ15v6q3eF8mUBVQ6shmWz6AXGvufMDTfcG9DXYY9uADuenHg
        call_tx_hash: 
          type: string
          example: th_hRMgnKsDZonTx9FStnAtdimPJxuZrFdZdZoYagzTfisLZALqG
        call_txi: 
          type: integer
          example: 32508544
        contract_id:
          type: string
          example: ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z",
        contract_txi:
          type: integer
          example: 8392766
        function:
          type: string
          example: Oracle.query",
        height:
          type: integer
          example: 608269
        internal_tx:
          type: object
          example:
            fee: 0
            nonce: 0
            oracle_id: ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc
            query: 'YWtfdVRXZWdwZk42VWpBNHl6OFg0WlZSaTl4S0VZZVhISkRSWmNScnlUc1JIQUZvQnBMYTtodHRwczovL21haWwuZ29vZ2xlLmNvbS9tYWlsL3UvMC8jaW5ib3g='
            query_fee: 20000000000000
            query_id": oq_2T4mYmjcyinbfYyHyDq6FfPXHChf5mYPEXgza9vHAukuq2EEHj
            query_ttl: 
              type: delta
              value": 20
            response_ttl:
              type: delta
              value: 20
            sender_id: ak_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4
            type: OracleQueryTx
            version: 1
        local_idx: 
          type: integer
          example: 0
        micro_index: 
          type: integer
          example: 2
    ContractLog:
      description: ContractLog
      properties:
        args: 
          type: array
          example:
            - 57632170077998225994387431184384351560267542170559996321319244663568556637966
            - 70455690283454580784062717387189552611484838031419336802117080415662207780030
            - 1050376320000000000
        block_hash: 
          type: string
          example: mh_27wa1cRsbEGV5N9N6BVKEtX1ycaomL5Q9w1NpL2iRjRt4aZhiV
        call_tx_hash:
          type: string
          example: th_DXhneXz8xk1RW2rSWtjzMFBsqkQ7qwhZzzYbdumq3hiZJHPig
        call_txi: 
          type: integer
          example: 32530611
        contract_id: 
          type: string
          example: ct_y7gojSY8rXW6tztE9Ftqe3kmNrqEXsREiPwGCeG3MJL38jkFo",
        contract_txi:
          type: integer
          example: 23524907
        data: 
          type: string
          example: ""
        event_hash:
          type: string
          example: "48U3JOKTVTI6FVMTK2BLHM8NG72JEBG93VS6MENPSC8E71IM5FNG===="
        ext_caller_contract_id: 
          type: string
          example: ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq
        ext_caller_contract_txi:
          type: integer
          example: 20366741
        height: 
          type: integer
          example: 609854
        log_idx:
          type: integer
          example: 0
        micro_index: 
          type: integer
          example: 15
        parent_contract_id: 
          type: integer
          nullable: true
          example: null
    Name:
      description: Name
      properties:
        active:
          type: boolean
          example: true
        hash: 
          type: string
          example: nm_2YmgvoUhVua9wEYGpMj9ybctbQXHPbY9Ppu4CoKoUm8jjFfcsc
        info:
          type: object
          properties:
            active_from: 
              type: integer
              example: 163282
            claims:
              type: array
              items: 
                type: integer
              example:
                - 4793600
                - 4792073
                - 4780558
                - 4750560
            expire_height:
              type: integer
              example: 362026
            ownership:
              type: object
              properties:
                current: 
                  type: string
                  example: ak_25BWMx4An9mmQJNPSwJisiENek3bAGadze31Eetj4K4JJC8VQN
                original: 
                  type: string
                  example: ak_pMwUuWtqDoPxVtyAmWT45JvbCF2pGTmbCMB4U5yQHi37XF9is
            pointers:
              type: object
              properties:
                account_pubkey: 
                  type: string
                  example: ak_25BWMx4An9mmQJNPSwJisiENek3bAGadze31Eetj4K4JJC8VQN
            transfers:
              type: array
              items: 
                type: integer
              example:
                - 11861568
                - 11860267
            updates:
              type: array
              items:
                type: integer
              example: 
                - 15509041
                - 15472510
                - 15436683
                - 15399850
                - 15363107
                - 15327260
                - 15292125
                - 15255201
                - 15218294
                - 15182623
                - 15145666
                - 15106041
                - 15103138
                - 15102422
                - 15034493
                - 14998378
                - 14962285
                - 14926110
                - 14889735
                - 14853605
                - 14816113
                - 14780302
                - 14734948
                - 14697934
                - 14660004
                - 14622742
                - 14585275
                - 14549202
                - 14512586
                - 14475599
                - 14433402
                - 14395593
                - 14359214
                - 14322121
                - 14275361
                - 14237928
                - 14197055
                - 14158176
                - 14118957
                - 14083790
                - 14047637
                - 14007331
                - 13968434
                - 13929634
                - 13888411
                - 13852034
                - 13729934
                - 13692516
                - 13655299
                - 13621141
                - 13585850
                - 13549286
                - 13517014
                - 13478966
                - 13119079
                - 13119035
                - 13119002
                - 13118969
                - 13118936
                - 12758156
                - 12758112
                - 12432743
                - 12432718
                - 12432693
                - 12432668
                - 12432643
                - 12077832
                - 10477629
                - 7255087
                - 4831909
        name:
          type: string
          example: trustwallet.chain
        previous:
          type: array
          items:
            $ref: '#/components/schemas/Name'
        status: 
          type: string
          enum:
            - name
            - auction
          example: name
    Auction:
      description: Auction
      properties:
        active:
          type: boolean
          example: false
        info:
          type: object
          properties:
            auction_end:
              type: integer
              example: 638002
            bids:
              type: array
              items:
                type: integer
              example:
                - 32508400
            last_bid:
              type: object
              properties:
                block_hash:
                  type: string
                  example: mh_28pH6wARaeMcdvMfe7nMJV2yYQMP9E36mmk6g9r9kkpEgao9MQ
                block_height:
                  type: integer
                  example: 608242
                hash:
                  type: string
                  example: th_2FAG7SHx4FkEBwh5dxjd2As3d7xXPZ3AZTQKFxm2sKADYpvDf6
                micro_index: 
                  type: integer
                  example: 2
                micro_time:
                  type: integer
                  example: 1654251750088
                signatures:
                  type: array
                  items:
                    type: string
                    example: sg_VXb4ipxdLk5PxfoQ6xUv9ma3GGmmMSARsRbXeWdS8cAGZS5SVdkfJgLskSw7rXzZSikGwha23LzsK7LPrDomkohRZTcb8
                tx:
                  type: object
                  example:
                    account_id: ak_2JJNMYcnqPaABiSY5omockmv4cCoZefv4XzStAxKe9gM2xYz2r
                    fee: 16540000000000
                    name: 1996.chain
                    name_fee: 134626900000000000000
                    name_id: nm_aJcPv1zMt3gdvxk6CQocaHq48D5vUyZXTqmwv2yXTTmk8fm2c
                    name_salt: 7095609104934055
                    nonce: 225,
                    ttl: 818002
                    type: NameClaimTx
                    version: 2
            tx_index:
              type: integer
              example: 32508400
            name:
              type: string
              example: 1996.chain
            previous:
              $ref: '#/components/schemas/Auction'
            status:
              enum:
                - auction
    Oracle:
      example:
        active: false
        active_from: 4660
        expire_height: 6894
        extends:
          - 11025
        format:
          query: string
          response: string
        oracle: ok_R7cQfVN15F5ek1wBSYaMRjW2XbMRKx7VDQQmbtwxspjZQvmPM
        query_fee: 20000
        register: 11023
      properties:
        active:
          description: The oracle active status
          type: boolean
        active_from:
          description: The block height when the oracle became active
          type: integer
        expire_height:
          description: The block height when the oracle expires
          type: integer
        extends:
          description: The tx indexes when the oracle has been extended
          type: array
          items:
            type: object
            description: The oracle's query and response formats
            example:
              query: string
              response: string
            properties:
              query:
                description: The query format
                type: string
              response:
                description: The response format
                type: string
            required:
              - response
              - query
        oracle:
          description: The oracle id
          type: string
        query_fee:
          description: The query fee
          type: integer
        register:
          description: The tx index when the oracle is registered
          type: integer
      required:
        - register
        - query_fee
        - oracle
        - format
        - extends
        - expire_height
        - active_from
        - active
      type: object
    Transfer:
      type: object
      properties:
        account_id: 
          type: string
          example: ak_2KAcA2Pp1nrR8Wkt3FtCkReGzAi8vJ9Snxa4PcmrthVx8AhPe8
        amount:
          type: integer
          example: 9592000000000000000
        height:
          type: integer
          example: 610158
        kind:
          enum:
            - reward_dev
            - reward_block
        ref_txi:
          type: integer
          nullable: true
          example: null
paths:
  /blocks:
    get:
      deprecated: false
      description: Get multiple blocks.
      operationId: get_blocks
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated blocks
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/Block'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /blocks/{hash_or_kbi}:
    get:
      deprecated: false
      description: Get a single block.
      operationId: get_block
      parameters:
        - name: hash_or_kbi
          in: path
          description: The block encoded hash or key block index
          required: true
          schema:
            oneOf:
              - type: string
                example: kh_22BuVBCFvW5FvQu3F8h4v351SfJPokR9ytwAD77Lyuo6mqxeeF
              - type: integer
                example: 123
      responses:
        '200':
          description: Returns a single block
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /blocks/{kbi}/{mbi}:
    get:
      deprecated: false
      description: Get a single block.
      operationId: get_block_by_mbi
      parameters:
        - name: kbi
          in: path
          description: The block key block index
          required: true
          schema:
            type: integer
            example: 123
        - name: mbi
          in: path
          description: The block micro block index, starting from 0
          required: true
          schema:
            type: integer
            example: 456
      responses:
        '200':
          description: Returns a single block
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /txs:
    get:
      deprecated: false
      description: Get multiple transactions.
      operationId: get_txs
      parameters:
        - name: type
          description: The transaction type. The query allows providing of multiple type parameters. [More info](https://github.com/aeternity/ae_mdw#types)
          in: query
          style: form
          explode: true
          schema:
            type: array
            items:
              enum:
                - channel_close_mutual
                - channel_close_solo
                - channel_create
                - channel_deposit
                - channel_force_progress
                - channel_offchain
                - channel_settle
                - channel_slash
                - channel_snapshot_solo
                - channel_withdraw
                - contract_call
                - contract_create
                - ga_attach
                - ga_meta
                - name_claim
                - name_preclaim
                - name_revoke
                - name_transfer
                - name_update
                - oracle_extend
                - oracle_query
                - oracle_register
                - oracle_response
                - paying_for
                - spend
          required: false
          x-example: channel_create
        - name: type_group
          description: The type group. The query allows providing of multiple type group parameters. [More info](https://github.com/aeternity/ae_mdw#types)
          in: query
          style: form
          explode: true
          schema:
            type: array
            items:
              enum:
                - channel
                - contract
                - ga
                - name
                - oracle
                - paying_for
                - spend
              type: string
          required: false
          x-example: channel
        - name: account
          description: The account ID. [More info](https://github.com/aeternity/ae_mdw#generic-ids)
          in: query
          required: false
          schema:
            type: string
          x-example: ak_g5vQK6beY3vsTJHH7KBusesyzq9WMdEYorF8VyvZURXTjLnxT
        - name: contract
          description: The contract ID. [More info](https://github.com/aeternity/ae_mdw#generic-ids)
          in: query
          required: false
          schema:
            type: string
          x-example: ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z
        - name: channel
          description: The channel ID. [More info](https://github.com/aeternity/ae_mdw#generic-ids)
          in: query
          required: false
          schema:
            type: string
          x-example: ch_22usvXSjYaDPdhecyhub7tZnYpHeCEZdscEEyhb2M4rHb58RyD
        - name: oracle
          description: The oracle ID. [More info](https://github.com/aeternity/ae_mdw#generic-ids)
          in: query
          required: false
          schema:
            type: string
          x-example: ok_24jcHLTZQfsou7NvomRJ1hKEnjyNqbYSq2Az7DmyrAyUHPq8uR
        - name: sender_id
          description: The sender ID
          example: ak_26dopN3U2zgfJG4Ao4J4ZvLTf5mqr7WAgLAq6WxjxuSapZhQg5
          in: query
          required: false
          schema:
            type: string
        - name: recipient_id
          description: The recipient ID
          example: ak_r7wvMxmhnJ3cMp75D8DUnxNiAvXs8qcdfbJ1gUWfH8Ufrx2A2
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'

      responses:
        '200':
          description: Returns paginatinated transactions
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/Tx'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /txs/{hash_or_index}:
    get:
      deprecated: false
      description: Get a single transaction.
      operationId: get_tx
      parameters:
        - name: hash_or_index
          in: path
          description: The transaction encoded hash or index (txi)
          required: true
          schema:
            type: string
            example: th_2Twp3pJeVuwQ7cMSdPQRfpAUWwdMiwx6coVMpRaNSuzFRnDZFk
      responses:
        '200':
          description: Returns single transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tx'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /txs/count:
    get:
      deprecated: false
      description: Get count of transactions at the latest height.
      operationId: get_tx_count
      responses:
        '200':
          description: Returns count of all transactions at the latest height
          content:
            application/json:
              schema:
                description: The transactions count
                example: 15479090
                type: integer
  /txs/count/{id}:
    get:
      deprecated: false
      description: Get transactions count and its type for given aeternity ID.
      operationId: get_tx_count_by_id
      parameters:
        - description: The ID of the address/name/oracle/etc
          in: path
          name: id
          required: true
          schema:
            type: string
            x-example: ak_g5vQK6beY3vsTJHH7KBusesyzq9WMdEYorF8VyvZURXTjLnxT
      responses:
        '200':
          description: Response schema for transactions count by id
          content:
            application/json:
              example:
                oracle_extend_tx:
                  oracle_id: 2
                oracle_query_tx:
                  oracle_id: 2
                  sender_id: 2
                oracle_register_tx:
                  account_id: 1
                oracle_response_tx:
                  oracle_id: 2
                spend_tx:
                  recipient_id: 1
                  sender_id: 2
              schema:
                type: object
                properties:
                  channel_close_mutual_tx:
                    type: object
                    description: The channel close mutual txs count
                  channel_close_solo_tx:
                    type: object
                    description: The channel close solo txs count
                  channel_create_tx:
                    type: object
                    description: The channel create txs count
                  channel_deposit_tx:
                    type: object
                    description: The channel deposit txs count
                  channel_force_progress_tx:
                    type: integer
                    description: The channel force progress txs count
                  channel_offchain_tx:
                    type: object
                    description: The channel offchain txs count
                  channel_settle_tx:
                    type: object
                    description: The channel settle txs count
                  channel_slash_tx:
                    type: object
                    description: The channel slash txs count
                  channel_snapshot_solo_tx:
                    type: object
                    description: The channel snapshot solo txs count
                  channel_withdraw_tx:
                    type: object
                    description: The channel withdraw txs count
                  contract_call_tx:
                    type: object
                    description: The contract call txs count
                  contract_create_tx:
                    type: object
                    description: The contract create txs count
                  ga_attach_tx:
                    type: object
                    description: The ga attach txs count
                  ga_meta_tx:
                    type: object
                    description: The ga meta txs count
                  name_claim_tx:
                    type: object
                    description: The name claim txs count
                  name_preclaim_tx:
                    type: object
                    description: The name preclaim txs count
                  name_revoke_tx:
                    type: object
                    description: The name revoke txs count
                  name_transfer_tx:
                    type: integer
                    description: The name transfer txs count
                  name_update_tx:
                    type: object
                    description: The name update txs count
                  oracle_extend_tx:
                    type: object
                    description: The oracle extend txs count
                  oracle_query_tx:
                    type: object
                    description: The oracle query txs count
                  oracle_register_tx:
                    type: object
                    description: The oracle register txs count
                  oracle_response_tx:
                    type: object
                    description: The oracle response txs count
                  paying_for_tx:
                    type: object
                    description: The paying for txs count
                  spend_tx:
                    type: object
                    description: The spend txs count
        
        
        
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /deltastats:
    get:
      deprecated: false
      description: Get delta stats.
      operationId: get_deltastats
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated delta stats per generation
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/DeltaStat'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /totalstats:
    get:
      deprecated: false
      description: Get total accumulated stats.
      operationId: get_totalstats
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated total stats per generation
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/TotalStat'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /contracts/logs:
    get:
      deprecated: false
      description: Get contract logs.
      operationId: get_contracts_logs
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated contracts logs
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/ContractLog'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /contracts/calls:
    get:
      deprecated: false
      description: Get contract calls.
      operationId: get_contracts_calls
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated contracts logs
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/ContractCall'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /names:
    get:
      deprecated: false
      description: Get multiple names.
      operationId: get_names
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated names
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/Name'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /names/search:
    get:
      deprecated: false
      description: Get multiple names.
      operationId: search_names
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated active/inactive names and auctions
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          allOf:
                            - $ref: '#/components/schemas/Name'
                            - type: object
                              properties:
                                status:
                                  enum:
                                    - auction
                                    - active
                                    - inactive
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /names/auctions:
    get:
      deprecated: false
      description: Get multiple names.
      operationId: get_names_auctions
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated active/inactive names and auctions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /names/{id}:
    get:
      deprecated: false
      description: Get a single name.
      operationId: get_name
      parameters:
        - name: id
          in: path
          description: The name
          required: true
          schema:
            type: string
            example: foo.chain
      responses:
        '200':
          description: Returns single name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Name'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /names/{id}/auction:
    get:
      deprecated: false
      description: Get name auction
      operationId: get_name_auction
      parameters:
        - name: id
          in: path
          description: The name
          required: true
          schema:
            type: string
            example: foo.chain
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns the name active auction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /names/{id}/pointers:
    get:
      deprecated: false
      description: Get name pointers
      operationId: get_name_pointers
      parameters:
        - name: id
          in: path
          description: The name
          required: true
          schema:
            type: string
            example: foo.chain
      responses:
        '200':
          description: Returns a mapping of the name pointers
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /names/{id}/pointees:
    get:
      deprecated: false
      description: Get name pointees
      operationId: get_name_pointees
      parameters:
        - name: id
          in: path
          description: The name
          required: true
          schema:
            type: string
            example: foo.chain
      responses:
        '200':
          description: Returns the name the active and inactive name pointees
          content:
            application/json:
              schema:
                type: object
                properties:
                  active:
                    type: object
                  inactive:
                    type: object
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /oracles:
    get:
      deprecated: false
      description: Get multiple oracles.
      operationId: get_oracles
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginatinated oracles
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/Oracle'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'              
  /oracle/{id}:
    get:
      deprecated: false
      description: Get a single oracle.
      operationId: get_oracle
      parameters:
        - name: id
          in: path
          description: The oracle
          required: true
          schema:
            type: string
            example: foo.chain
      responses:
        '200':
          description: Returns single oracle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oracle'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /transfers:
    get:
      deprecated: false
      description: Get multiple transfers.
      operationId: get_transfers
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/DirectionParam'
      responses:
        '200':
          description: Returns paginated names
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items: 
                          $ref: '#/components/schemas/Transfer'
                  - $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Bad request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  # /aex9
  # /aex9/:contract_id
  # /aex9/:contract_id/balances
  # /aex9/:contract_id/balances/:account_id
  # /aex9/account-balances/:account_id
  # /aex9/transfers/from/:sender
  # /aex9/transfers/to/:recipient
  # /aex9/transfers/from-to/:sender/:recipient
  # /aex9/:contract_id/balances/:account_id/history
